on:
  push:
    branches:
      - main

name: Pages 배포를 하자.

jobs:
  deploy:
    name: Pages 배포를 하자.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
      
      - name: 의존성을 설치해요
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Gatsby 프로젝트를 빌드해요
        run: |
          yarn build
      
      - name: 서비스를 Cloudflare pages에 배포해요
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: pages publish ./public --project-name=junghyeonsu-dev
