on:
  push:
    branches:
      - main

name: Pages 배포를 하자.

jobs:
  deploy:
    name: Pages 배포를 하자.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn
      
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Test content metadata
        run: yarn test

      - name: Typecheck
        run: yarn typecheck

      - name: Cache Gatsby `.cache` Folder
        uses: actions/cache@v4
        id: gatsby-cache-folder
        with:
          path: .cache
          key: ${{ runner.os }}-gatsby-${{ hashFiles('yarn.lock', 'gatsby-config.js', 'gatsby-node.js', 'gatsby/**', 'src/**') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-

      - name: Build Gatsby Project
        run: yarn build
        env:
          NODE_OPTIONS: --max-old-space-size=4096
          GATSBY_CPU_COUNT: 2
          GATSBY_TELEMETRY_DISABLED: "1"
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
      
      - name: 서비스를 Cloudflare pages에 배포해요
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: pages publish ./public --project-name=jinsoolve-blog
